services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wallet-app:latest
    container_name: Wallet-App
    ports:
      - "${HOST_PORT}:${SERVER_PORT}"
    depends_on:
      db-postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
        - ./config:/app/config
    networks:
      - wallet-network

  db-postgres:
    image: postgres:16-alpine
    container_name: Wallet-Postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wallet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  wallet-network:
    driver: bridge
